source 'https://github.com/CocoaPods/Specs.git'

target 'DDTAssertLog', :exclusive => true do
  pod "DDTAssertLog", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DDTAssertLog", :path => "../"

  
end
